language: python

install:
  - pip install -r docs/sphinx-requirements.txt
  - pip install codecov
  - pip install tox
  - pip install pytest-datadir

matrix:
  include:
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=qa

script:
  - tox
  
branches:
  only:
  - master
  - dev

after_success:
  - codecov
